[build]
  command = "npm run build"   
  publish  = "dist"

[build.environment]
  NODE_VERSION = "20"

# ---- PROXY: front-end /api/* -> Azure API /api/* ----
[[redirects]]
  from = "/api/*"
  to   = "https://library-api-project1-gpefacc9gg97dxgr.germanywestcentral-01.azurewebsites.net/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# (Optional) long cache for built assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
